name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'

jobs:
  build:
    name: Build and install
    runs-on: ubuntu-latest
    steps:
      - name: Install build requirements
        run: sudo apt-get update ; sudo apt-get install -y cmake gcc-12 pkg-config libjansson-dev

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Configure Intee build
        run: rm -rf build ; cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release

      - name: Build and install Intree
        run: cd build && make && sudo make install && sudo make uninstall
